<?php

/**
 * @file
 * Primary module hooks for reola module.
 */

use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;

 /**
 * Implements hook_theme().
 */
function reola_theme($existing, $type, $theme, $path) {
    return array (
      'block_map' => array (
          'variables' => array (
              'datos'=> NULL
          ),
          'template' => 'block_map'
        ),

     'block_ultimodato' => array (
          'variables' => array (
            'datos' => NULL
          ),
          'template' => 'block_ultimodato'
      ),

      'block_lastdatabig' => array(
          'variables' => array (
              'datos' =>NULL
          ),
          'template' => 'block_lastdatabig'
      ),


    );
  }

?>


